version: '3.8'

services:
  grokapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grokapp
    ports:
      - "8501:8501"
    environment:
      - GROK_API_KEY=${GROK_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
      - PINECONE_INDEX_NAME=${PINECONE_INDEX_NAME}
    volumes:
      - ./fonts:/app/fonts:ro
      - ./users.txt:/app/users.txt:ro
      - ./prompt.txt:/app/prompt.txt:ro
      - app_temp:/app/temp
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - grokapp-network

  redis:
    image: redis:7-alpine
    container_name: grokapp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - grokapp-network
    command: redis-server --appendonly yes

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: grokapp-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - grokapp
    restart: unless-stopped
    networks:
      - grokapp-network
    profiles:
      - production

volumes:
  redis_data:
  app_temp:

networks:
  grokapp-network:
    driver: bridge