# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://www.azure.com/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build n Deploy App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10.18
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.18'

      # IMPORTANT: Removed virtual environment creation and dependency installation.
      # Azure App Service will handle 'pip install -r requirements.txt' during deployment.

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      # If your tests require dependencies, you would set up a separate venv ONLY for testing
      # within this step, ensuring it's not packaged for deployment.

      - name: Zip artifact for deployment
        # This will now only zip your application code, requirements.txt, etc., NOT installed dependencies or the venv.
        run: zip release.zip ./* -r -x "venv/*" -x ".git/*" -x "__pycache__/*" -x ".github/*" # Exclude venv, .git, __pycache__, and the workflow file directory itself

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip # Only upload the single zip file

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_31F431932D3E4CE887FA68AABD8B79E1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_854D8374AF744C70BF74C632931E9662 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_976E893F1B0E4D619B76C4448D5C4CE0 }}

      - name: Delay before deploy
        # This delay might not be necessary with the smaller package, but can be kept if desired.
        run: sleep 60

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'grokappfinance'
          slot-name: 'Production'
          package: release.zip
